services:
  app:
    build: .
    environment:
      - TOKEN=${TOKEN}
      - DB_PASS=${DB_PASS}
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./trigger:/app/trigger

  db:
    image: mariadb:11.5.2
    environment:
      - MARIADB_USER=default
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=boarbot
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u default -p\"${DB_PASS}\" -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: