on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release:
    name: Create Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.ACTION_KEY }}
    
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Get the PR title and body
        id: pr_info
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_TITLE_ESCAPED=$(echo "$PR_TITLE" | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "PR_TITLE=$PR_TITLE_ESCAPED" >> $GITHUB_ENV

          PR_BODY="${{ github.event.pull_request.body }}"
          PR_BODY_ESCAPED=$(echo "$PR_BODY" | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "PR_BODY=$PR_BODY_ESCAPED" >> $GITHUB_ENV

          if [[ "${{ github.event.pull_request.title }}" =~ v?([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            
            if [[ ! "${{ github.event.pull_request.title }}" =~ ^v ]]; then
              VERSION="v$VERSION"
            fi
            
            echo "Extracted version: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "No valid version found in PR title."
            echo "VERSION=" >> $GITHUB_ENV
          fi

      - name: Create Release
        if: env.VERSION != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.PR_TITLE }}
          body: ${{ env.PR_BODY }}
